# Generated by Django 4.2.4 on 2023-08-17 13:16

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("categories", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Promotion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=100, unique=True, verbose_name="نام"),
                ),
                (
                    "description",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="توضیحات"
                    ),
                ),
                (
                    "discount_rate",
                    models.IntegerField(default=0, verbose_name="درصد تخفیف"),
                ),
                (
                    "create_datetime",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="تاریخ و زمان ایجاد"
                    ),
                ),
                (
                    "start_datetime",
                    models.DateTimeField(verbose_name="تاریخ و زمان آغاز"),
                ),
                (
                    "end_datetime",
                    models.DateTimeField(verbose_name="تاریخ و زمان پایان"),
                ),
                (
                    "category",
                    models.ManyToManyField(
                        to="categories.category", verbose_name="دسته\u200cبندی"
                    ),
                ),
            ],
            options={
                "db_table": "promotion",
                "ordering": ("-end_datetime",),
            },
        ),
    ]
