# Generated by Django 4.2.4 on 2023-08-17 13:16

import brands.models
from django.db import migrations, models
import django.db.models.functions.text
import django_lifecycle.mixins


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Brand",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=100, unique=True, verbose_name="نام"),
                ),
                (
                    "url",
                    models.SlugField(
                        blank=True, max_length=100, unique=True, verbose_name="لینک"
                    ),
                ),
                (
                    "country",
                    models.CharField(blank=True, max_length=30, verbose_name="کشور"),
                ),
                ("description", models.TextField(blank=True, verbose_name="توضیحات")),
                (
                    "meta_title",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="عنوان متا"
                    ),
                ),
                (
                    "meta_description",
                    models.TextField(blank=True, verbose_name="توضیحات متا"),
                ),
                (
                    "main_image",
                    models.ImageField(
                        blank=True,
                        upload_to=brands.models.Brand.get_upload_path,
                        verbose_name="تصویر",
                    ),
                ),
                (
                    "create_datetime",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="تاریخ و زمان ایجاد"
                    ),
                ),
                (
                    "update_datetime",
                    models.DateTimeField(
                        auto_now=True, verbose_name="تاریخ و زمان آخرین ویرایش"
                    ),
                ),
            ],
            options={
                "db_table": "brand",
                "ordering": ("name",),
                "indexes": [
                    models.Index(
                        django.db.models.functions.text.Lower("name"),
                        name="lower_brand_name_idx",
                    ),
                    models.Index(
                        django.db.models.functions.text.Lower("country"),
                        name="lower_brand_country_idx",
                    ),
                ],
            },
            bases=(django_lifecycle.mixins.LifecycleModelMixin, models.Model),
        ),
    ]
