# Generated by Django 4.2.4 on 2023-08-25 14:06

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("comments", "0002_remove_comment_rating_comment_like"),
    ]

    operations = [
        migrations.AlterField(
            model_name="comment",
            name="like",
            field=models.IntegerField(
                default=0,
                editable=False,
                validators=[
                    django.core.validators.MinValueValidator(0),
                    django.core.validators.MaxValueValidator(5),
                ],
                verbose_name="تعداد لایک",
            ),
        ),
    ]
