# Generated by Django 4.2.4 on 2023-10-02 03:39

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("comments", "0003_alter_comment_like"),
    ]

    operations = [
        migrations.AddField(
            model_name="comment",
            name="published",
            field=models.BooleanField(default=True, verbose_name="وضعیت انتشار"),
        ),
    ]
