# Generated by Django 4.2.4 on 2023-10-02 19:29

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("comments", "0011_comment_published"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="comment",
            name="like",
        ),
        migrations.AddField(
            model_name="comment",
            name="likes_count",
            field=models.PositiveIntegerField(
                default=0, editable=False, verbose_name="تعداد لایک\u200cها"
            ),
        ),
    ]
