# Generated by Django 4.2.4 on 2023-08-17 13:16

from django.db import migrations, models
import django.db.models.deletion
import django.db.models.functions.text
import django_lifecycle.mixins


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "create_datetime",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="تاریخ و زمان ایجاد"
                    ),
                ),
                (
                    "update_datetime",
                    models.DateTimeField(
                        auto_now=True, verbose_name="تاریخ و زمان آخرین ویرایش"
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="نام")),
                (
                    "url",
                    models.SlugField(
                        allow_unicode=True,
                        blank=True,
                        max_length=100,
                        verbose_name="لینک",
                    ),
                ),
                ("description", models.TextField(blank=True, verbose_name="توضیحات")),
                (
                    "meta_title",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="عنوان متا"
                    ),
                ),
                (
                    "meta_description",
                    models.TextField(blank=True, verbose_name="توضیحات متا"),
                ),
                (
                    "media_folder_name",
                    models.CharField(max_length=100, verbose_name="نام پوشه مدیا"),
                ),
                (
                    "parent_category",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="subcategories",
                        to="categories.category",
                        verbose_name="دسته\u200cبندی والد",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Categories",
                "db_table": "category",
                "ordering": ("name",),
                "indexes": [
                    models.Index(
                        django.db.models.functions.text.Lower("name"),
                        name="lower_category_name_idx",
                    )
                ],
                "unique_together": {
                    ("parent_category", "url"),
                    ("parent_category", "name"),
                },
            },
            bases=(django_lifecycle.mixins.LifecycleModelMixin, models.Model),
        ),
    ]
