# Generated by Django 4.2.4 on 2023-08-17 13:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_lifecycle.mixins


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("products", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Address",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("address", models.TextField(max_length=1000, verbose_name="نشانی")),
                (
                    "postal_code",
                    models.CharField(max_length=100, verbose_name="کد پستی"),
                ),
                (
                    "house_number",
                    models.CharField(
                        blank=True, max_length=50, null=True, verbose_name="شماره پلاک"
                    ),
                ),
                (
                    "unit_number",
                    models.CharField(
                        blank=True, max_length=50, null=True, verbose_name="شماره واحد"
                    ),
                ),
                (
                    "receiver_first_name",
                    models.CharField(
                        blank=True, max_length=50, verbose_name="نام گیرنده"
                    ),
                ),
                (
                    "receiver_last_name",
                    models.CharField(
                        blank=True, max_length=50, verbose_name="نام خانوادگی گیرنده"
                    ),
                ),
                (
                    "phone_number",
                    models.CharField(max_length=50, verbose_name="شماه تلفن"),
                ),
                (
                    "is_default",
                    models.BooleanField(
                        default=False, verbose_name="تنظیم به عنوان آدرس پیشفرض"
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Addresses",
                "db_table": "address",
            },
            bases=(django_lifecycle.mixins.LifecycleModelMixin, models.Model),
        ),
        migrations.CreateModel(
            name="OrderStatus",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.IntegerField(
                        choices=[
                            (0, "پرداخت ناموفق"),
                            (1, "پرداخت موفق"),
                            (2, "در حال آماده سازی"),
                            (3, "ارسال شده"),
                            (4, "تحویل داده شده"),
                        ],
                        verbose_name="وضعیت سفارش",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Order Statuses",
                "db_table": "order_status",
                "ordering": ("status",),
            },
        ),
        migrations.CreateModel(
            name="PaymentMethod",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50, verbose_name="نام")),
                (
                    "provider",
                    models.CharField(
                        blank=True, max_length=50, verbose_name="ارائه دهنده"
                    ),
                ),
            ],
            options={
                "db_table": "payment_method",
                "ordering": ("name",),
            },
        ),
        migrations.CreateModel(
            name="Region",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=50, unique=True, verbose_name="استان"),
                ),
            ],
            options={
                "db_table": "region",
                "ordering": ("name",),
            },
        ),
        migrations.CreateModel(
            name="ShippingMethod",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50, verbose_name="نام")),
                (
                    "provider",
                    models.CharField(
                        blank=True, max_length=50, verbose_name="ارائه دهنده"
                    ),
                ),
                (
                    "cost",
                    models.DecimalField(
                        decimal_places=3, default=0, max_digits=10, verbose_name="قیمت"
                    ),
                ),
            ],
            options={
                "db_table": "shipping_method",
                "ordering": ("name",),
            },
        ),
        migrations.CreateModel(
            name="Order",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "create_datetime",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="تاریخ و زمان ایجاد"
                    ),
                ),
                (
                    "order_code",
                    models.BigIntegerField(db_index=True, verbose_name="کد سفارش"),
                ),
                (
                    "tracking_code",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="کد رهگیری مرسوله پستی"
                    ),
                ),
                (
                    "tax_cost",
                    models.DecimalField(
                        decimal_places=3,
                        default=0,
                        max_digits=15,
                        verbose_name="هزینه مالیات",
                    ),
                ),
                (
                    "shipping_cost",
                    models.DecimalField(
                        decimal_places=3, max_digits=10, verbose_name="هزینه ارسال"
                    ),
                ),
                (
                    "total_cost",
                    models.DecimalField(
                        decimal_places=3,
                        default=0,
                        max_digits=18,
                        verbose_name="مبلغ کل",
                    ),
                ),
                (
                    "payment_datetime",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="تاریخ و زمان پرداخت"
                    ),
                ),
                (
                    "delivery_datetime",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="تاریخ و زمان تحویل"
                    ),
                ),
                (
                    "address",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="orders.address",
                        verbose_name="نشانی",
                    ),
                ),
                (
                    "payment_method",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="orders.paymentmethod",
                        verbose_name="روش پرداخت",
                    ),
                ),
                (
                    "shipping_method",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="orders.shippingmethod",
                        verbose_name="روش ارسال",
                    ),
                ),
                (
                    "status",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="orders.orderstatus",
                        verbose_name="وضعیت",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="orders",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="کاربر",
                    ),
                ),
            ],
            options={
                "db_table": "order",
                "ordering": ("-create_datetime",),
            },
            bases=(django_lifecycle.mixins.LifecycleModelMixin, models.Model),
        ),
        migrations.CreateModel(
            name="City",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(db_index=True, max_length=50, verbose_name="شهر"),
                ),
                (
                    "region",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="cities",
                        to="orders.region",
                        verbose_name="استان",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Cities",
                "db_table": "city",
                "ordering": ("name",),
                "unique_together": {("region", "name")},
            },
        ),
        migrations.AddField(
            model_name="address",
            name="city",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="orders.city",
                verbose_name="شهر",
            ),
        ),
        migrations.AddField(
            model_name="address",
            name="region",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="orders.region",
                verbose_name="استان",
            ),
        ),
        migrations.AddField(
            model_name="address",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="addresses",
                to=settings.AUTH_USER_MODEL,
                verbose_name="کاربر",
            ),
        ),
        migrations.CreateModel(
            name="OrderItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "create_datetime",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="تاریخ و زمان ایجاد"
                    ),
                ),
                ("name", models.CharField(max_length=255, verbose_name="نام")),
                (
                    "price",
                    models.DecimalField(
                        decimal_places=3, max_digits=15, verbose_name="قیمت"
                    ),
                ),
                (
                    "total_price",
                    models.DecimalField(
                        decimal_places=3, max_digits=18, verbose_name="قیمت کل"
                    ),
                ),
                ("quantity", models.IntegerField(default=1, verbose_name="تعداد")),
                (
                    "order",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="orders.order",
                        verbose_name="سفارش",
                    ),
                ),
                (
                    "product_item",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="products.productitem",
                        verbose_name="محصول",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="کاربر",
                    ),
                ),
            ],
            options={
                "db_table": "order_item",
                "unique_together": {("order", "product_item")},
            },
            bases=(django_lifecycle.mixins.LifecycleModelMixin, models.Model),
        ),
    ]
