# Generated by Django 4.2.4 on 2023-08-17 13:16

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("orders", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="orderitem",
            name="create_datetime",
        ),
    ]
