# Generated by Django 4.2.4 on 2023-08-26 15:45

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("orders", "0002_remove_orderitem_create_datetime"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="order_code",
            field=models.BigIntegerField(
                db_index=True, editable=False, verbose_name="کد سفارش"
            ),
        ),
    ]
