# Generated by Django 4.2.4 on 2023-08-17 13:16

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django_lifecycle.mixins
import products.models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("categories", "0001_initial"),
        ("brands", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Attribute",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=50, unique=True, verbose_name="نام"),
                ),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="attributes",
                        to="categories.category",
                        verbose_name="دسته\u200cبندی",
                    ),
                ),
            ],
            options={
                "db_table": "attribute",
                "ordering": ("name",),
            },
        ),
        migrations.CreateModel(
            name="AttributeValue",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "char_value",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        null=True,
                        verbose_name="متن کوتاه (حداکثر ۲۵۵ کاراکتر)",
                    ),
                ),
                (
                    "text_value",
                    models.TextField(blank=True, null=True, verbose_name="متن بلند"),
                ),
                (
                    "int_value",
                    models.IntegerField(blank=True, null=True, verbose_name="عدد صحیح"),
                ),
                (
                    "decimal_value",
                    models.DecimalField(
                        blank=True,
                        decimal_places=3,
                        max_digits=10,
                        null=True,
                        verbose_name="عدد اعشاری",
                    ),
                ),
                (
                    "date_value",
                    models.DateField(blank=True, null=True, verbose_name="تاریخ"),
                ),
                (
                    "time_value",
                    models.TimeField(blank=True, null=True, verbose_name="زمان"),
                ),
                (
                    "attribute",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="values",
                        to="products.attribute",
                        verbose_name="ویژگی",
                    ),
                ),
            ],
            options={
                "db_table": "attribute_value",
                "ordering": ("attribute",),
            },
        ),
        migrations.CreateModel(
            name="Product",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "create_datetime",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="تاریخ و زمان ایجاد"
                    ),
                ),
                (
                    "update_datetime",
                    models.DateTimeField(
                        auto_now=True, verbose_name="تاریخ و زمان آخرین ویرایش"
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=255, unique=True, verbose_name="نام"),
                ),
                (
                    "url",
                    models.SlugField(
                        allow_unicode=True,
                        blank=True,
                        max_length=255,
                        unique=True,
                        verbose_name="لینک",
                    ),
                ),
                ("introduction", models.TextField(blank=True, verbose_name="معرفی")),
                ("review", models.TextField(blank=True, verbose_name="نقد و بررسی")),
                (
                    "meta_title",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="عنوان متا"
                    ),
                ),
                (
                    "meta_description",
                    models.TextField(blank=True, verbose_name="توضیحات متا"),
                ),
                (
                    "main_image",
                    models.ImageField(
                        upload_to=products.models.Product.product_directory_path,
                        verbose_name="تصویر اصلی",
                    ),
                ),
                (
                    "is_available",
                    models.BooleanField(
                        choices=[(True, "موجود"), (False, "ناموجود")],
                        db_index=True,
                        default=False,
                        verbose_name="وضعیت موجودی",
                    ),
                ),
                (
                    "is_visible",
                    models.BooleanField(
                        choices=[(True, "نمایش داده شود"), (False, "نمایش داده نشود")],
                        db_index=True,
                        default=False,
                        verbose_name="وضعیت نمایش",
                    ),
                ),
                (
                    "dimension",
                    models.CharField(blank=True, max_length=255, verbose_name="ابعاد"),
                ),
                (
                    "weight",
                    models.CharField(blank=True, max_length=255, verbose_name="وزن"),
                ),
                (
                    "included_items",
                    models.TextField(blank=True, verbose_name="اقلام همراه"),
                ),
                (
                    "other_features",
                    models.TextField(blank=True, verbose_name="ویژگی\u200cهای دیگر"),
                ),
                (
                    "other_description",
                    models.TextField(blank=True, verbose_name="سایر توضیحات"),
                ),
                (
                    "rating",
                    models.DecimalField(
                        decimal_places=1,
                        default=0,
                        editable=False,
                        max_digits=2,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(5),
                        ],
                        verbose_name="امتیاز",
                    ),
                ),
                (
                    "comments_count",
                    models.IntegerField(default=0, verbose_name="تعداد نظرات"),
                ),
                (
                    "views_count",
                    models.IntegerField(
                        default=0, editable=False, verbose_name="تعداد بازدیدها"
                    ),
                ),
                (
                    "sold_count",
                    models.IntegerField(
                        default=0, editable=False, verbose_name="تعداد فروخته شده"
                    ),
                ),
                (
                    "brand",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="products",
                        to="brands.brand",
                        verbose_name="برند",
                    ),
                ),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="products",
                        to="categories.category",
                        verbose_name="دسته\u200cبندی",
                    ),
                ),
            ],
            options={
                "db_table": "product",
                "ordering": ("-is_available", "-id"),
            },
            bases=(django_lifecycle.mixins.LifecycleModelMixin, models.Model),
        ),
        migrations.CreateModel(
            name="ProductMedia",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "file",
                    models.FileField(
                        upload_to=products.models.ProductMedia.product_directory_path,
                        verbose_name="فایل",
                    ),
                ),
                (
                    "type",
                    models.IntegerField(
                        choices=[(1, "عکس"), (2, "فیلم")], verbose_name="نوع فایل"
                    ),
                ),
                (
                    "alternate_text",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="متن جایگزین"
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="media_files",
                        to="products.product",
                        verbose_name="محصول",
                    ),
                ),
            ],
            options={
                "db_table": "product_media",
                "ordering": ("-id",),
            },
            bases=(django_lifecycle.mixins.LifecycleModelMixin, models.Model),
        ),
        migrations.CreateModel(
            name="ProductItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "sku",
                    models.CharField(
                        blank=True,
                        max_length=50,
                        null=True,
                        unique=True,
                        verbose_name="شناسه کالا",
                    ),
                ),
                (
                    "original_price",
                    models.DecimalField(
                        decimal_places=3,
                        default=0,
                        max_digits=15,
                        verbose_name="قیمت اصلی",
                    ),
                ),
                (
                    "selling_price",
                    models.DecimalField(
                        decimal_places=3,
                        default=0,
                        max_digits=15,
                        verbose_name="قیمت فروش",
                    ),
                ),
                (
                    "inventory",
                    models.PositiveIntegerField(default=0, verbose_name="موجودی انبار"),
                ),
                (
                    "is_available",
                    models.BooleanField(
                        choices=[(True, "موجود"), (False, "ناموجود")],
                        db_index=True,
                        default=False,
                        verbose_name="وضعیت موجودی",
                    ),
                ),
                (
                    "is_visible",
                    models.BooleanField(
                        choices=[(True, "نمایش داده شود"), (False, "نمایش داده نشود")],
                        db_index=True,
                        default=False,
                        verbose_name="وضعیت نمایش",
                    ),
                ),
                (
                    "configuration",
                    models.ManyToManyField(
                        db_table="product_item_configuration",
                        to="products.attributevalue",
                        verbose_name="پیکربندی",
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="products.product",
                        verbose_name="محصول",
                    ),
                ),
            ],
            options={
                "db_table": "product_item",
                "ordering": ("-is_available", "-id"),
            },
            bases=(django_lifecycle.mixins.LifecycleModelMixin, models.Model),
        ),
    ]
