# Generated by Django 4.2.4 on 2023-08-21 15:54

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("products", "0002_alter_product_rating"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="product",
            options={"ordering": ("-is_visible", "-is_available", "-id")},
        ),
        migrations.AlterField(
            model_name="product",
            name="comments_count",
            field=models.IntegerField(
                default=0, editable=False, verbose_name="تعداد نظرات"
            ),
        ),
    ]
