# Generated by Django 4.2.4 on 2023-08-22 13:28

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("products", "0003_alter_product_options_alter_product_comments_count"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="productitem",
            options={"ordering": ("-is_visible", "-is_available", "-id")},
        ),
    ]
